Support offline private tally in ledger
input-output-hk/chain-libs pull request #520
Opened 2021-02-01 12:59 UTC by eugene-babichenko

2021-02-02 09:29 UTC, mzabaluev requested changes

2021-02-02 09:29 UTC, mzabaluev commented on chain-impl-mockchain/src/certificate/vote_tally.rs
> +    pub tally_result: Box<[u64]>,
Shouldn't the result be included just once? It does not need to be duplicated per each share.

2021-02-02 09:32 UTC, mzabaluev commented on chain-impl-mockchain/src/certificate/vote_tally.rs
> +    pub tally_result: Box<[u64]>,
Sorry, confused about the array's dimensions.

2021-02-02 10:19 UTC, mzabaluev approved these changes

2021-02-02 10:52 UTC, eugene-babichenko commented on chain-impl-mockchain/src/certificate/vote_tally.rs
>                              bb.u8(n_members)
Strictly speaking, it doesn't contradict the tallying algorithm. But overall this is an interesting idea.

2021-02-05 09:31 UTC, mzabaluev commented on chain-impl-mockchain/src/certificate/vote_tally.rs
>                              bb.u8(n_members)
The treasury voting protocol paper stipulates that decryption shares from every committee member are either provided or recovered by posting shares of their communication keys. Not sure if the recovered shares need to be separately posted on the blockchain, though; so let it stay this way.

2021-02-08 14:02 UTC, mzabaluev approved these changes

2021-02-08 14:03 UTC, merged