Add decryption share verification
input-output-hk/chain-libs pull request #542
Opened 2021-03-13 10:29 UTC by vincenthz

* introduce a decryption nizk
* introduce a new `verify_decrypt_share` to verify decrypt share using the decryption nizk
* change format of tallydecryptshare to contains the proof
* also finish is now randomized due to randomized nizk

2021-04-08 14:19 UTC, iquerejeta reviewed
I would recommend making some changes in the way we define the ZKPs. One way I see it is by defining the low level ZKPs (such as discrete log) in `chain-crypto`, and the more specific (such as correct decryption proof) here. This would allow us to use DLEQ proof in other contexts.  

I feel it's confusing to be in the context of a discrete logarithm proof, and have variables called `share`, `decrypted_share` or `pk`. In my opinion it would be clearer to explicitly distinguish between the discrete log proof and the decryption proof, as the former might be used in a context different correct decryption

2021-04-08 16:12 UTC, iquerejeta commented on chain-vote/src/lib.rs
> +            let decrypted_share = r1 * &secret_key.0.sk;
This is also computed within the `generate()` function. We could pass it as input to avoid computing it twice.

2021-04-12 10:08 UTC, iquerejeta requested changes
Generator and public key should be given as input of the challenge computation

2021-04-29 06:17 UTC, mzabaluev commented on chain-vote/src/decr_nizk.rs
> +pub fn generate(w: &Scalar, share: &GroupElement, sk: &Scalar) -> Proof {
Will this make `rand` (or another RNG library) an explicit dependency? OTOH you probably need it anyway to come up with the random input.

My take is, if the proof is sensitive to the choice of a random value or the value is derived from other input data, make it internal to the API.

2021-05-12 14:34 UTC, iquerejeta commented on chain-vote/src/decr_nizk.rs
> +/// Generate a decryption zero knowledge proof
Can't we use the proof in `chain-crypto/src/algorithms/vrf/dleq.rs`?

2021-06-15 14:17 UTC, mzabaluev commented
Superseded by #574.

2021-06-15 14:17 UTC, closed without merging