[Test] Add API tests
input-output-hk/chain-libs pull request #608
Opened 2021-07-26 08:10 UTC by mrzenioszeniou

Introduced two API tests:
1. Verifies that after a transaction in a ledger **without** fees, the total funds do not change and the fee pots remain empty.
2. Verifies that after a transaction in a ledger **with** fees, the total funds do not change and the fee pots contain the fee.

2021-07-27 08:48 UTC, dkijania requested changes

2021-07-27 08:48 UTC, dkijania commented on chain-impl-mockchain/src/testing/e2e/fees/mod.rs
> +fn transaction_without_fees() {
Looks like those two methods are almost the same in term of the flow. the only diff is FEE value. Maybe we should introduce helper method with signature:

`fn verify_total_funds_after_transaction_with_fee(fee: u64)`

and then use it for two cases (non zero fees and zero fees).

2021-07-27 08:48 UTC, dkijania commented on chain-impl-mockchain/src/testing/e2e/fees/mod.rs
> +    const ALICE: &str = "Alice";
This is my mistake, done in some earlier PR, but you can fix it in this one. Please consider moving ALICE and BOB consts to the module level and use it in all tests in current module

2021-07-27 08:48 UTC, dkijania commented
Apart above minor remarks code looks very good

2021-07-28 14:17 UTC, mrzenioszeniou reviewed
@dkijania, I noticed that`chain-impl-mockchain/src/testing/e2e/fees` was redundant since it only contained a `mod.rs` file. I moved it up to `e2e` to get rid of the unnecessary nesting.

2021-07-29 08:44 UTC, dkijania approved these changes

2021-07-29 09:42 UTC, merged