[Test] cover gaps in Leadership tests
input-output-hk/chain-libs pull request #654
Opened 2021-10-01 07:45 UTC by dkijania

2021-10-01 08:35 UTC, Zeegomo requested changes

2021-10-01 08:35 UTC, Zeegomo commented on chain-impl-mockchain/src/header/builder.rs
> +    pub fn sign_using_unsafe(self, sk: &SecretKey<Ed25519>, pk: PublicKey<Ed25519>) -> HeaderBft {
Can we make this a test-only interface?

2021-10-05 11:56 UTC, dkijania commented on chain-impl-mockchain/src/header/builder.rs
> +    pub fn sign_using_unsafe(self, sk: &SecretKey<Ed25519>, pk: PublicKey<Ed25519>) -> HeaderBft {
Fixed that, according to our discussion

2021-10-06 10:05 UTC, Zeegomo approved these changes

2021-10-06 10:33 UTC, merged